### ISSUE TITLE
Creating a new Branch and making a MR to Master?

### ISSUE THREAD

**Issue by RicardoMonteiroSimoes** [andstor/copycat-action#25]
I've stumbled upon this action which seems to be exactly what I want. I'm working on a Project that uses ReactJS frontend + RoR backend. To keep things separate, we are using 2 separate repositories.
What I'm trying to do with CopyCat is automating the code transfer from frontend -> backend.

It seems to work as intended, but the problem is that CopyCat can't create a new branch on the target repository. This would make things much better for everyone. Maybe even make it create an automatic merge request?

**Comment by RicardoMonteiroSimoes** [comment]
This is my current action:
https://github.com/UnifiedCalculation/UniCalc_Frontend/runs/524584405

And I am greeted with following message:
```
Cloning into 'UniCalc_Frontend'...
Copying "UniCalc_Frontend//src/components/" and pushing it to UnifiedCalculation/UniCalc_Frontend
Cloning into 'UniCalc_backend'...
warning: Could not find remote branch updateReactComponents to clone.
fatal: Remote branch updateReactComponents not found in upstream origin
Cloning 'UnifiedCalculation/UniCalc_backend' failed
```

**Comment by RicardoMonteiroSimoes** [comment]
I created a branch on the backend repository with the same name, and it works afterwards. 

Enhancement idea:
- Allow for the creation of a new branch if it doesnt exist
- Allow for the automatic creation of a merge request from the new branch to a given branch, best done trough a variable

**Comment by andstor** [comment]
Hi,
glad you got it working 👌

Thanks for your feedback. It is much appreciated!
As for your ideas:
> * Allow for the creation of a new branch if it doesn't exist

I agree. If the remote branch in the destination repo does not exist, we should create a new one based on the default branch.

> * Allow for the automatic creation of a merge request from the new branch to a given branch, best done trough a variable

I see that automatically creating a *Pull Request* for the copying procedure could be of value. However, I think this is better achieved by using a separate GitHub Action in the destination repo for creating the Pull Requests. For example [pull-request-action](https://github.com/marketplace/actions/github-pull-request-action).

**Comment by RicardoMonteiroSimoes** [comment]
> Allow for the automatic creation of a merge request from the new branch to a given branch, best done trough a variable

I can fully understand this. I even tried using actions in the target repo for both of those actions: *Creating a new branch* and *creating a pull request*. The problem ended up being that you would need to constantly pull from the currently active branch into the target branch, which would end up in a mess code wise.

There  for I agree that the simple creation of a branch would suffice in this case, and then a normal action on the target repo could react upon a commit with a certain keyword or whatever.

**Comment by RicardoMonteiroSimoes** [comment]
@andstor I've got some free time on my hands, I'll do a fork and try to implement it, should be pretty straight forward.

**Comment by andstor** [comment]
Great!

**Comment by andstor** [comment]
Closing this since "the creation of the destination branch if it doesn't exists" has been resolved in PR #34

**Comment by spencer741** [comment]
For those who find this issue in the future, make sure that, if you don't provide the ` src_branch` and/or `dst_branch` args, your default branch names should both be "master". Otherwise you'll get an error very similar to the OP of this issue.

I ran into this issue because GitHub started naming the default master branch "main". Took me a while of just staring at my yaml before it hit me that `copycat-action` was looking for a "master" branch by default when my default branch was named "main". 

So, if you follow Github's new default branch naming, you need to specify the appropriate args for this GitHub action. 

Reference:
``` yaml
src_branch:
    description: 'The branch name of the source repository'
    required: false
    default: 'master'
  dst_branch:
    description: 'The branch name of the destination repository'
    required: false
    default: 'master'
```

I might make a PR to add this to the readme, since it's very easy to look over.

**Comment by andstor** [comment]
@spencer741 please do create a PR addressing the change in GitHub's new default branch naming in the README 👍 

We should also consider also changing the default to use `main` instead of `master`. However, this would require a new major version release. Please open a new issue concerning this specifically so we could review different solutions. Maybe it is possible to check whether a repo uses the `master` or `main` naming scheme in some reliable way?
